name: FFC Class Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: '43 23 * * 0'
    - cron: '43 22 * * 2'
    - cron: '28 22 * * 3'
    - cron: '43 15 * * 4'
    - cron: '58 12 * * 5'

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python reminder.py
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TRIGGERED_CRON: ${{ github.event.schedule }}
